### ISSUE TITLE
not working after updates

### ISSUE THREAD

**Issue by Cupcakes123** [Fukki/auto-shit#1]

**Comment by Cupcakes123** [comment]
https://gyazo.com/c34c6f79d24924130b0bf9bb7186159e
https://gyazo.com/81b29f99cf01acf425249c24052e9392

**Comment by motuson** [comment]
me too

**Comment by Fukki** [comment]
maybe your region not patch 8x now
or some problem in proxy data parser
because this packet is new version
btw i just put old version if your region not patch 8x

**Comment by Cupcakes123** [comment]
ohh, yeah NA doesn't have it yet
