### ISSUE TITLE
in case you're not aware! thank you!

### ISSUE THREAD

**Issue by Cupcakes123** [Fukki/auto-shit#2]
[dispatch] handle: failed to parse S_LOGIN<13>
hook: (anonymous) in auto shit
data: b701b85c31015701200077014000332a0000ed000910008000000910000005270000000000000100000000340000006e000000651901050a1401000100440000000000b30000000000000002000000040000000100000000000000000026e558080e00000074ec77d903000000f36d49f20700000009000000b90b0000000000000000000000000000d9ca370c0000000000000000360f0300bd4c0000bf4c0000c04c000054c30200000000001d2503005b405e0000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000030c2020054ee0300000000006158ff2c010000000000000000640000000000803f000000004b0075007300680069006e0061002e005400680065002e0053006c006100790065007200000003101003030000061a101000140903000c100a100c1710141016160817100b10011710171710141414101010100f0f0f10130a001b1b090000000000000000000000000000000000000000000000000000000000000000000000000000000000
error: S_LOGIN<13>..unk: cannot find next element of array at 343 (found value 4099)
    at parseField (C:\Users\x\Desktop\Caalis\node_modules\tera-data-parser\lib\protocol\index.js:380:19)
    at TeraProtocol.parse (C:\Users\x\Caalis\node_modules\tera-data-parser\lib\protocol\index.js:431:7)

**Comment by Fukki** [comment]
Fixed
